### ISSUE TITLE
Tool no longer works

### ISSUE THREAD

**Issue by Tachyonica** [eth2353/eth2.tax#1]
This amazing tool stopped working - now I only get "An error occurred, please try again. If the issue persists, check the browser console for more information." on all browsers :(

Please could you breathe life back into it - we love it!

Thanks.

**Comment by eth2353** [comment]
Hi there,

I'm aware of the issue, unfortunately I can't fix it immediately as the server that contains the rewards data is in a remote location and is not responding.

I will be at the location this Sunday around 6pm UTC and will get this back up and running. I've added a warning message to the website for now.

**Comment by Tachyonica** [comment]
Thanks so much! You are amazing!
