### ISSUE TITLE
Timezone selection

### ISSUE THREAD

**Issue by fimp** [eth2353/eth2.tax#10]
I believe it was previously possible to select a timezone for rewards calculation. Is this no longer possible?

**Comment by eth2353** [comment]
This is no longer possible. The space required by the database for storing this data was getting too big for me to maintain for all timezones.

If you absolutely need data for a specific timezone, you can always run the tool yourself and adjust the timezones in the following places:

https://github.com/eth2353/eth2.tax/blob/main/src/indexer/balances.py#L22 (indexer change)
https://github.com/eth2353/eth2.tax/blob/main/src/api/api_v1/endpoints/rewards.py#L29 (API change)
