### ISSUE TITLE
Tool hangs 

### ISSUE THREAD

**Issue by Tachyonica** [eth2353/eth2.tax#2]
On pressing "Calculate" the tool just hangs and no longer outputs anything.

**Comment by eth2353** [comment]
Hi, thanks for reporting, I am aware, unfortunately it will take me at least a few more hours to resolve. I'll add another comment here once the website's back up.

**Comment by Tachyonica** [comment]
I'm receiving Error: {"detail":""}

**Comment by Tachyonica** [comment]
Working! :)

**Comment by eth2353** [comment]
I checked the logs but couldn't see anything weird happening today, so I really have no idea how that would happen :)
