### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Tachyonica** [eth2353/eth2.tax#8]
Hi! I'm getting an error message when using your awesome app. Any ideas why it might be happening? Thanks!

**Comment by eth2353** [comment]
Hi, my node went down again 😕 it’s happening very randomly, I suspect a HW issue but I haven’t figured it out yet.

I’m on vacation and unable to reboot it remotely right away. It should be back up and running around noon UTC on Wednesday.

**Comment by eth2353** [comment]
Hey Tachyonica,

I moved the DB to the cloud and have switched to using Infura to update the balances daily. This way the website can stay up and be stable while I figure out why my node at home keeps crashing.

I'll close this issue as everything is working again. Have a good one!
